version: '3.3'
services:
  auth:
    container_name: authentication
    build: .
    networks:
      - redis_net
      - postgres_net
      - ingress_net
    env_file:
      - ../.env
    environment:
      - VIRTUAL_HOST=auth.staging.hi-verse.com
      - LETSENCRYPT_HOST=auth.staging.hi-verse.com
    healthcheck:
      test: curl --fail http://127.0.0.1/api/health || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
networks:
  redis_net:
    external: true
  postgres_net:
    external: true
  ingress_net:
    external: true
